import os
base = r'C:\Users\HP\Desktop\certificatavril2\conduite\ophtalmologie'

files = {
'dacryocystite.html':'''<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><title>Dacryocystite - Ophtalmologie</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Segoe UI",sans-serif;background-color:#f5f5f5;padding:20px}.container{background:white;border-radius:15px;width:100%;max-width:800px;margin:0 auto}.header{background:linear-gradient(135deg,#9b59b6,#8e44ad);color:white;padding:30px;text-align:center}.header h1{font-size:2em}.content{padding:30px}.section{margin-bottom:25px}.section-title{color:#9b59b6;font-size:1.3em;margin-bottom:15px;border-bottom:2px solid #9b59b6}.clinical-box,.treatment-box{background:#f9f9f9;border-radius:10px;padding:20px}.clinical-box{border-left:4px solid #e74c3c}.treatment-box{border-left:4px solid #27ae60}.back-button{display:inline-block;background:#9b59b6;color:white;padding:12px 25px;border-radius:25px;text-decoration:none;margin-top:20px}</style>
</head>
<body><div class="container"><div class="header"><h1>Dacryocystite</h1><div class="subtitle">Ophtalmologie - Dr. KHERBA N</div></div><div class="content"><div class="section"><h2 class="section-title">Clinique</h2><div class="clinical-box"><p><strong>Inflammation du sac lacrymal</strong></p><ul><li>Larmoiment clair puis purulent</li><li>Unilatérale puis bilatérale</li></ul></div></div><div class="section"><h2 class="section-title">Traitement</h2><div class="treatment-box"><ul><li><strong>Rifamycine collyre</strong> - 1gtt 4/j pdt 10j</li><li><strong>Vitbact collyre</strong> - 2gtt 6/j pdt 10j</li><li><strong>ATB per os</strong></li></ul></div></div><a href="index.html" class="back-button"> Retour à l'index</a></div></div></body>
</html>''',
'episclerite.html':'''<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><title>Episclérite - Ophtalmologie</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Segoe UI",sans-serif;background-color:#f5f5f5;padding:20px}.container{background:white;border-radius:15px;width:100%;max-width:800px;margin:0 auto}.header{background:linear-gradient(135deg,#9b59b6,#8e44ad);color:white;padding:30px;text-align:center}.header h1{font-size:2em}.content{padding:30px}.section{margin-bottom:25px}.section-title{color:#9b59b6;font-size:1.3em;margin-bottom:15px;border-bottom:2px solid #9b59b6}.clinical-box,.treatment-box{background:#f9f9f9;border-radius:10px;padding:20px}.clinical-box{border-left:4px solid #e74c3c}.treatment-box{border-left:4px solid #27ae60}.back-button{display:inline-block;background:#9b59b6;color:white;padding:12px 25px;border-radius:25px;text-decoration:none;margin-top:20px}</style>
</head>
<body><div class="container"><div class="header"><h1>Episclérite</h1><div class="subtitle">Ophtalmologie - Dr. KHERBA N</div></div><div class="content"><div class="section"><h2 class="section-title">Clinique</h2><div class="clinical-box"><p><strong>Maladie inflammatoire bénigne et spontanément résolutive</strong></p><ul><li>1er épisode: Bénin</li><li>Récidives: Rechercher maladie de système</li></ul></div></div><div class="section"><h2 class="section-title">Traitement</h2><div class="treatment-box"><ul><li><strong>Indocollyre coll</strong> - 1gtt 4/j</li><li><strong>Maxidrol collyre</strong> - 1gtt 3/j</li><li><strong>Maxidrol pmd</strong> - 1app/j le soir</li></ul></div></div><a href="index.html" class="back-button"> Retour à l'index</a></div></div></body>
</html>''',
'herpes-ophtalmique.html':'''<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><title>Herpès ophtalmique - Ophtalmologie</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Segoe UI",sans-serif;background-color:#f5f5f5;padding:20px}.container{background:white;border-radius:15px;width:100%;max-width:800px;margin:0 auto}.header{background:linear-gradient(135deg,#9b59b6,#8e44ad);color:white;padding:30px;text-align:center}.header h1{font-size:2em}.content{padding:30px}.section{margin-bottom:25px}.section-title{color:#9b59b6;font-size:1.3em;margin-bottom:15px;border-bottom:2px solid #9b59b6}.clinical-box,.treatment-box{background:#f9f9f9;border-radius:10px;padding:20px}.clinical-box{border-left:4px solid #e74c3c}.treatment-box{border-left:4px solid #27ae60}.back-button{display:inline-block;background:#9b59b6;color:white;padding:12px 25px;border-radius:25px;text-decoration:none;margin-top:20px}</style>
</head>
<body><div class="container"><div class="header"><h1>Herpès ophtalmique</h1><div class="subtitle">Ophtalmologie - Dr. KHERBA N</div></div><div class="content"><div class="section"><h2 class="section-title">Signes infectieux</h2><div class="clinical-box"><ul><li>Rougeur</li><li>Douleur</li></ul></div></div><div class="section"><h2 class="section-title">Traitement</h2><div class="treatment-box"><ul><li><strong>Aciclosina pmd</strong> - 1app 3/j pdt 10j</li></ul></div></div><a href="index.html" class="back-button"> Retour à l'index</a></div></div></body>
</html>''',
'myiase-oculaire.html':'''<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><title>Myiase oculaire - Ophtalmologie</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Segoe UI",sans-serif;background-color:#f5f5f5;padding:20px}.container{background:white;border-radius:15px;width:100%;max-width:800px;margin:0 auto}.header{background:linear-gradient(135deg,#9b59b6,#8e44ad);color:white;padding:30px;text-align:center}.header h1{font-size:2em}.content{padding:30px}.section{margin-bottom:25px}.section-title{color:#9b59b6;font-size:1.3em;margin-bottom:15px;border-bottom:2px solid #9b59b6}.clinical-box,.treatment-box{background:#f9f9f9;border-radius:10px;padding:20px}.clinical-box{border-left:4px solid #e74c3c}.treatment-box{border-left:4px solid #27ae60}.back-button{display:inline-block;background:#9b59b6;color:white;padding:12px 25px;border-radius:25px;text-decoration:none;margin-top:20px}</style>
</head>
<body><div class="container"><div class="header"><h1>Myiase oculaire</h1><div class="subtitle">Ophtalmologie - Dr. KHERBA N</div></div><div class="content"><div class="section"><h2 class="section-title">Clinique</h2><div class="clinical-box"><p><strong>Présence de larves de mouches</strong></p></div></div><div class="section"><h2 class="section-title">Traitement</h2><div class="treatment-box"><ul><li><strong>Tobrex/Chibroxine/Desomedine coll</strong> - 1app 5/j</li><li><strong>Clomycine pmd</strong> - 1app 2/j</li><li><strong>Siccafluid</strong></li><li><strong>Pansement oculaire</strong></li></ul></div></div><a href="index.html" class="back-button"> Retour à l'index</a></div></div></body>
</html>''',
'orgelet.html':'''<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><title>Orgelet - Ophtalmologie</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Segoe UI",sans-serif;background-color:#f5f5f5;padding:20px}.container{background:white;border-radius:15px;width:100%;max-width:800px;margin:0 auto}.header{background:linear-gradient(135deg,#9b59b6,#8e44ad);color:white;padding:30px;text-align:center}.header h1{font-size:2em}.content{padding:30px}.section{margin-bottom:25px}.section-title{color:#9b59b6;font-size:1.3em;margin-bottom:15px;border-bottom:2px solid #9b59b6}.clinical-box,.treatment-box{background:#f9f9f9;border-radius:10px;padding:20px}.clinical-box{border-left:4px solid #e74c3c}.treatment-box{border-left:4px solid #27ae60}.back-button{display:inline-block;background:#9b59b6;color:white;padding:12px 25px;border-radius:25px;text-decoration:none;margin-top:20px}</style>
</head>
<body><div class="container"><div class="header"><h1>Orgelet</h1><div class="subtitle">Ophtalmologie - Dr. KHERBA N</div></div><div class="content"><div class="section"><h2 class="section-title">Clinique</h2><div class="clinical-box"><p><strong>Infection d'un follicule du cil</strong></p><p>Petite boule contenant du pus. Rouge et douloureux.</p></div></div><div class="section"><h2 class="section-title">Traitement (15 jours)</h2><div class="treatment-box"><ul><li><strong>Rifa
